"""Add cron_schedule

Revision ID: 5153cd748e43
Revises: 0cf9f006ba9f
Create Date: 2026-01-08 22:56:45.634948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5153cd748e43'
down_revision: Union[str, Sequence[str], None] = '0cf9f006ba9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('cron_schedule', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'cron_schedule')
    # ### end Alembic commands ###
