"""Add execution_timeout

Revision ID: 88e726fdc66a
Revises: 87dd3a7df766
Create Date: 2026-01-07 14:12:59.859013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e726fdc66a'
down_revision: Union[str, Sequence[str], None] = '87dd3a7df766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('execution_timeout', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'execution_timeout')
    op.drop_column('jobs', 'started_at')
    # ### end Alembic commands ###
