"""Add tenant table

Revision ID: b1b2b3b4b5b6
Revises: 87dd3a7df766
Create Date: 2026-01-08 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1b2b3b4b5b6'
down_revision: Union[str, Sequence[str], None] = '87dd3a7df766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('max_inflight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # For now we add the FK. 
    # NOTE: If existing jobs have tenant_id that doesn't exist, this will fail.
    # We assume clean slate or valid tenants.
    op.create_foreign_key('fk_jobs_tenant_id_tenants', 'jobs', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_tenant_id_tenants', 'jobs', type_='foreignkey')
    op.drop_table('tenants')
    # ### end Alembic commands ###
